### PR TITLE
Enable pstore to capture reboot causes

### PR DESCRIPTION
**Pull request by fhunleth**
The pstore provides an in-memory buffer that can capture logs, kernel
oops and other information when unexpected reboots. The buffer is
recovered on the next boot where it can be inspected. This commit only
enables the drivers and allocates a 1 MB region in memory for storage.
User code is still needed to send more log information and retreive
logs.

### CODE REVIEW

**Comment by fhunleth** [comment]
@ConnorRigby Thanks for posting your rpi3 version. It was really helpful in making this one. I've tested this lightly and it seems good and doesn't cause my rpi0 to overheat or anything weird like that.

**Comment by ConnorRigby** [comment]
Lol the over heating of my rpi3 was unrelated to the pstore change

**Comment by mobileoverlord** [comment]
This looks good, we should stage these across all rpi* systems and then test and merge at the same time.

**Comment by fhunleth** [comment]
I've been using this periodically and it seems good. It definitely needs some library and documentation help to make it generally accessible.

**Pull request merged**
