### PR TITLE
Add linter

### PR DESCRIPTION
**Pull request by ConnorRigby**
This does the following:
* Adds the linter as a dep
* Runs the linter on CI

### CODE REVIEW

**Comment by tmecklem** [comment]
The output from the linter in the failed category is:

```
Failed checks:

ensure_package: BR2_PACKAGE_FWUP: false
```

Is this something that should be addressed or is it a false positive?

**Comment by ConnorRigby** [comment]
im actually not sure about that. @fhunleth is there a reason `BR2_PACKAGE_FWUP` is not enabled?

**Comment by fhunleth** [comment]
Sorry, I updated `nerves_system_br` to automatically pull in `fwup` just like it automatically pulls in `erlang` when `nerves-config` enabled. That seemed like an easy way to totally avoid the issue of leaving `fwup` out, and I did it some time around when you were working on the linter.

I know that I have to take a pass at the linter warnings. I'll try to do that tonight or first thing tomorrow morning.

**Comment by tmecklem** [comment]
@ConnorRigby thank you for the linter work. Seems like it will be very useful. Is it the correct expectation that we will eventually fail the CircleCI system builds for `Failed checks`?

**Comment by ConnorRigby** [comment]
Yeah. Right now it exits with a exit status of 0 no matter what but it would be simple to allow a exit status argument.

**Comment by fhunleth** [comment]
Very glad that we're finally getting this integrated!!

**Pull request merged**
